Bug Resolve header map
iptomar/RaulLinoA pull request #31
Opened 2023-04-11 17:17 UTC by Rubenm83

Resolução do BUG - Header Map

2023-04-11 21:16 UTC, rDg06 reviewed
É possivel o mapa ocupar as linhas a vermelho?
![image](https://user-images.githubusercontent.com/55752257/231290046-e2fee691-a3e3-497e-a6d2-a6931c8681cc.png)

2023-04-11 22:01 UTC, rDg06 approved these changes
Aprovado e testado

2023-04-11 22:59 UTC, GoncaloAlpalhao requested changes
Estão a definir o tamanho do mapa estaticamente, isso causa problemas entre dispositivos. Tenta usar o match_parent para width e um wrap_content para height para se adaptar de dispositivo para dispositivo

2023-04-12 17:06 UTC, GoncaloAlpalhao approved these changes
Perfect now 💯

2023-04-12 17:07 UTC, merged

2023-04-12 17:07 UTC, rDg06 approved these changes
Aprovado