Nota biográfica
iptomar/RaulLinoA pull request #53
Opened 2023-04-21 00:49 UTC by SSw4rtzz

O fragmento 'fragment_biography' foi estruturado com elementos da biografia de Raul Lino, à semelhança do modelo fornecido.

Validem por favor se as margens estão dinâmicas!

2023-04-21 08:27 UTC, hgoncal2 requested changes
Tanto no emulador,como no telemóvel, o header aparece-me desformatado
![Screenshot_1](https://user-images.githubusercontent.com/101368171/233584774-3d019854-7ac1-46d1-83de-5964e9eb64b1.jpg)
E o primeiro bloco de texto não está alinhado
![Screenshot_2](https://user-images.githubusercontent.com/101368171/233585733-7aafc49e-f877-4bac-bf1a-b89797c1c732.jpg)

2023-04-21 12:46 UTC, rDg06 requested changes
Tens de fazer o include do header como está no detalhe do edificio

2023-04-21 17:39 UTC, SSw4rtzz commented
Adicionei uma _ScrollView_ a todo o conteúdo do fragmento, permitindo que em ecrãs mais pequenos seja possível ver tudo.

Adicionei também o include do header, como mencionado
> Tens de fazer o include do header como está no detalhe do edificio


Penso que desta vez tenha ficado certo

<img width="221" alt="Captura de ecrã 2023-04-21, às 18 16 28" src="https://user-images.githubusercontent.com/16618607/233699513-ced9c825-9303-471f-a693-6b4bab4777e4.png"><img width="228" alt="Captura de ecrã 2023-04-21, às 18 17 40" src="https://user-images.githubusercontent.com/16618607/233699543-fba726f0-d0b9-405e-b5b7-bc8207d2e47a.png">

2023-04-21 21:37 UTC, GoncaloAlpalhao commented
Ainda existe um problema que não acontece no emulador, só em alguns telemóveis. No tablet tá perfeito 👌
Suponho que o @SSw4rtzz não consegue resolver sozinho pois ele está mais dependente do emulador.
![Screenshot_20230421_222622_Raul Lino](https://user-images.githubusercontent.com/101589711/233737349-6e7838c3-c642-4618-83c3-c65b4675eb82.jpg)
![Screenshot_20230421_223306_Raul Lino](https://user-images.githubusercontent.com/101589711/233738216-f9bae7c2-6409-4966-805b-7bf32dc4b406.jpg)

2023-04-22 07:32 UTC, hgoncal2 approved these changes
Parece-me bem

2023-04-22 14:21 UTC, Rubenm83 approved these changes
De acordo 💯

2023-04-22 17:32 UTC, FranciscoCarvalho2001 approved these changes
Aprovado

2023-04-23 17:37 UTC, GoncaloAlpalhao commented
Hello maltinha, já andei a mexer  na image view para que se fosse adaptando de ecrã para ecrã para que não haja texto cortado em ecrãs menores. Utilizei um ratio de 60% para a image view - 40% para o texto.
Segue uma print com, da esquerda pra direita, Tablet - Telemóvel - Emulador
![image](https://user-images.githubusercontent.com/101589711/233855583-3f6a497e-13bb-4c20-b25f-2725023186ab.png)

2023-04-23 17:38 UTC, GoncaloAlpalhao approved these changes
Para mim agora está tudo ótimo 🚀

2023-04-24 10:37 UTC, rDg06 approved these changes
Aprovado

2023-04-24 14:48 UTC, merged