Desenhar itinerario
iptomar/RaulLinoA pull request #68
Opened 2023-05-24 17:41 UTC by Rubenm83

Implementação - Desenhar Dois Itenerários

2023-05-24 17:43 UTC, GoncaloAlpalhao approved these changes
Top 🤙

2023-05-24 17:49 UTC, rDg06 requested changes
Se possivel mudar a cor para roxo a mesma cor do icon 
![image](https://github.com/iptomar/RaulLinoA/assets/55752257/c8cfe06b-123d-48b2-8a49-4eca570c8547)

O segundo itinerario não está correto e a cor se for possivel tambem mudar 
![image](https://github.com/iptomar/RaulLinoA/assets/55752257/a39f2ef5-ad00-45da-a58c-87513acf27ec)

2023-05-24 19:31 UTC, Rubenm83 commented
Alteração do Itenerário & Mudança de Cor
![raulLino](https://github.com/iptomar/RaulLinoA/assets/39858074/2d8d899a-c154-4fb9-9b7f-c0e88f92bee4) , validem novamente sff

2023-05-24 19:50 UTC, FranciscoCarvalho2001 approved these changes
Aprovado 💯

2023-05-25 08:36 UTC, rDg06 requested changes
Não puseste a linha com a mesma cor do botão, está trocado e para o utilizador vai se tornar confuso

2023-05-25 09:47 UTC, rDg06 approved these changes
Aprovado e testado

2023-05-25 09:54 UTC, merged